### ISSUE TITLE
[Bug] Alarm rings before arrival 

### ISSUE THREAD

**Issue by hegzploit** [AbdeltwabMF/loc#20]
The alarm has started ringing midway into the trip, I rebooted the device and sat the alarm again it started ringing instantly, not sure of the cause.
Let me know If I can provide any type of logging.

**Comment by AbdeltwabMF** [comment]
Do you use the beta version?

**Comment by hegzploit** [comment]
yea, that's what caused the bug.

On Feb 27, 2023 4:58 PM, "Abd El-Twab M. Fakhry" ***@***.***> wrote:

Do you use the beta version?

**Comment by AbdeltwabMF** [comment]
The beta version has multiple bugs 🤕 and is not ready yet for use
