### ISSUE TITLE
package renamed?

### ISSUE THREAD

**Issue by IzzySoft** [AbdeltwabMF/Loc#61]
It seems with v0.6.4 the `applicationId` changed from `org.abdeltwabmf.loc` to `xyz.abdeltwabmf.loc` – which essentially means this is a different app. Thus "updates" to v0.6.4 are not possible; one has to uninstall and re-install, with all data/configuration lost. Was that intended, or did something go wrong here? Release notes do not mention a rename. The related commit can be found in #53, but it doesn't have any comments what it is supposed to "hotfix".

Note this also affects your listing in my repo as well as your inclusion request at F-Droid (see #1). If there's no strong reason, `applicationId` should not be changed once an app is public – it's more than a "cosmetic change", it has some implications as you see :wink:

**Comment by AbdeltwabMF** [comment]
Yes, that was intended. The reason why I've to change it is that the old domain was by mistake, and there is no config related to the old versions of the app. And you're right, I forgot to add this to the release notes.

**Comment by IzzySoft** [comment]
OK, then I'll have to "move" your app's listing accordingly. Hope it won't affect too many users (and that the `applicationId` now will remain :wink:). Thanks for clarification!
