### ISSUE TITLE
not compatible with Pixel 7 Pro

### ISSUE THREAD

**Issue by moduletz** [AbdeltwabMF/Loc#63]
"App not installed as app isn't compatible with your phone"

The Pixel 7 lineup is only compatible with 64 bit apps, could you please update it?

**Comment by AbdeltwabMF** [comment]
There is already a universal release that is compatible with all architectures. Did you try it?

**Comment by moduletz** [comment]
You're right, I got confused with the naming scheme. Well, thank you!
